### PR TITLE
0.59.2

### PR DESCRIPTION
**Pull request by celandro**
Update for latest version of protobufs

### CODE REVIEW

**Comment by celandro** [comment]
Will have to manually merge. If people want to use this repo vs. mine thats fine but I will need to add some other people as mergers on the pogoprotos-java repo.

This merge pulls in the latest proto files and has a new version of the jar. One issue is that apparently they broke backwards compatibility on the pokemon go side and you cant read the old protos with the new jar. We may need to put the appropriate jar files for each release somewhere

java -cp target\pokemongo-game-master-2.8.0.jar com.pokebattler.gamemaster.GenerateJSON versions\0.57.1\GAME_MASTER.protobuf
Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.

**Comment by BrunnerLivio** [comment]
Thanks alot!

Looks like they're pending merge conflicts. Could you resolve them? I'll merge then.

**Comment by celandro** [comment]
I can't right now I'm at work and will be busy till Saturday but I managed
to sneak this pull request in this morning

**Comment by BrunnerLivio** [comment]
@celandro Dont worry! If someone complains, I'll figure something out, otherwise we'll wait untill Saturday.

**Comment by BrunnerLivio** [comment]
Whats the status of this PR?

**Comment by celandro** [comment]
I'm on vacation right now. I forgot about this. I don't think it's a
difficult merge

**Comment by BrunnerLivio** [comment]
@celandro Alright. Enjoy your holidays! :)

**Comment by celandro** [comment]
The protos updated again, will create a new one

**Pull request merged**
