### PR TITLE
New Latios move

### PR DESCRIPTION
**Pull request by celandro**

### CODE REVIEW

**Review by dandesousa — APPROVED** [review]

**Comment by dandesousa** [comment]
Looks like just the latest version file needs to be updated to pass the test?

**Comment by dandesousa** [comment]
If you don't fix it by tomorrow I'll push up the change to let ci build it. Not at a computer at the moment or I'd just do it.

**Comment by celandro** [comment]
sorry im really busy right now

**Comment by dandesousa** [comment]
No worries, didn't mean to bug ya about it just checking in as I saw a post on reddit about finding the latest.

Thank you for doing this!

**Comment by BrunnerLivio** [comment]
Ready to merge from my point of view

Waiting for your approval @celandro

**Pull request merged**
