### PR TITLE
Mewtwo stat changes

### PR DESCRIPTION
**Pull request by celandro**
Not sure what version number we are officially on right now but this has the correct mewtwo stats

### CODE REVIEW

**Comment by jophj** [comment]
I think the JSON file is the same 0.69.1 file

**Comment by celandro** [comment]
It's not. Mewtwo stats were changed on Sunday and I regenerated at that
time.

**Comment by jophj** [comment]
Then I don't know what I'm doing wrong. I was searching for the 0.69.2 json gamemaster but to me [this](https://raw.githubusercontent.com/BrunnerLivio/pokemongo-game-master/a1f5c993b391f28b44f392decc17fe8534bdf2ef/versions/0.69.2/GAME_MASTER.json) file looks exactly the same as [this](https://raw.githubusercontent.com/BrunnerLivio/pokemongo-game-master/a1f5c993b391f28b44f392decc17fe8534bdf2ef/versions/0.69.1/GAME_MASTER.json).

**Comment by celandro** [comment]
I'll check when I get to my computer but it's possible I only updated the
latest file and copied the 0.69.1 directory to 0.69.2 and forgot to copy
the latest file to the 0.69.2 directory

**Comment by celandro** [comment]
I dont know what happened, the files reverted on my machine. I must have screwed up a git pull at some point and wiped out my changes.

I reran and mewtwo now has 300 attack as expected.

**Comment by dandesousa** [comment]
Any reason this hasn't been merged? I use this for a personal project, but don't have access to an Android device ATM to pull the game master file. If we need help with PR reviews I'm happy to help.

**Review by dandesousa — APPROVED** [review]

**Comment by celandro** [comment]
Note that I havent regenerated a pure json from the Hidden Power Suicune change yet.

**Comment by dandesousa** [comment]
@celandro I know, I saw that -- thanks for merging I was going off the branch. I'm picking up a dev android device from a friend so I should be able to help out with keeping this up to date for whoever is using it -- perhaps I can take a shot at regenerating sometime this week if you don't get around to it.

thanks!

**Pull request merged**
