### PR TITLE
Game Master 0.79.4 and 0.83.3

### PR DESCRIPTION
**Pull request by dandesousa**
Adds two versions of the game master, the latter primarily just add new items (for sun + moon). Also adds Castform and Deoxys forms.

I'll update again when the new game master is updated for gen 3.

### CODE REVIEW

**Comment by celandro** [comment]
Think we should reject this. I have been working on importing all the new 0.85.1 protos and will be making a push as soon as gen 3 comes out.

Im going to push my branch. Perhaps merge that in and regenerate the jsons and then i can commit (if gen 3 doesnt come out in the next hour ;))

**Comment by celandro** [comment]
See https://github.com/BrunnerLivio/pokemongo-game-master/pull/24

**Comment by dandesousa** [comment]
👍

**Comment by dandesousa** [comment]
@celandro rebased my changes on the updated protos. Is that what you had in mind?

**Comment by celandro** [comment]
Yep much better. Numbers replaced with enum names hurray!

Gen 3 here we come

**Pull request merged**
