### PR TITLE
Updated to 0.97.2

### PR DESCRIPTION
**Pull request by khallmark**
Adds game_master version 0.97.2

### CODE REVIEW

**Comment by celandro** [comment]
Thanks for the pull request. While it looks like it was done correctly, and normally I would merge it, the actual protos have updated as well which took me some time to handle properly.

Closing in favor of https://github.com/BrunnerLivio/pokemongo-game-master/pull/42 as it is more complete.

**Comment by khallmark** [comment]
@celandro What did I do wrong so that I can do it correctly in the future? I almost always pull the new game_master as soon as it's available (within hours). I'm glad to push it out to the community.

**Comment by celandro** [comment]
Nothing wrong. You followed the instructions perfectly. The issue is that I
had already done the work to update the pogo java project with the latest
enums. There was no point merging your work in before I merged mine on top
and  clobbered everything.

Unless you want to learn how pogo java works, id keep doing what you are
doing.  This was only required to have the correct names for draco meteor
and the new weather ball moves. There were some other unimportant updates
as well but move names are critical for my project and others. Normally I
would have just accepted your pull request.

The way this project works, is it uses the compiled java protobufs to
transform the game master to json. The compiled Java protobufs use the
uncompiled pogoprotos project.

**Comment by celandro** [comment]
Nothing wrong. You followed the instructions perfectly. The issue is that I
had already done the work to update the pogo java project with the latest
enums. There was no point merging your work in before I merged mine on top
and  clobbered everything.

Unless you want to learn how pogo java works (and I don't think you do),
it's not necessary.  This was only required to have the correct names for
draco meteor and the new weather ball moves. There were some other
unimportant updates as well.

The way this project works, is it uses the compiled java protobufs to
transform the game master to json. The compiled Java protobufs use the
uncompiled pogoprotos project.

**Pull request closed without merging**
